spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  redis:
    port:
    host:
    #password:
    database: 0
    timeout: 3000
    redisson:
      database: 3
  # session失效时间（分钟)
  session:
    timeout: 86400 #两个月
    # 默认存在内存，改成存在redis，表示从redis读写session
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    context-path: /api #给后端所有服务访问地址加上api前缀
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted #全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

